// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOq4HcsFkWTTgxbLYId1mfoKakZSIluYI',
    appId: '1:816941767036:web:8c4a4504244ef30a77ecf9',
    messagingSenderId: '816941767036',
    projectId: 'notiskku-database',
    authDomain: 'notiskku-database.firebaseapp.com',
    storageBucket: 'notiskku-database.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYqmwUlGIkmIQ7dS_dDTv698WF3Bc2Gqo',
    appId: '1:816941767036:android:17a63096e1a90c2377ecf9',
    messagingSenderId: '816941767036',
    projectId: 'notiskku-database',
    storageBucket: 'notiskku-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq-Od_xMN-X82rQN67CdoWN0q0w-98DKs',
    appId: '1:816941767036:ios:06d40165f9dc685277ecf9',
    messagingSenderId: '816941767036',
    projectId: 'notiskku-database',
    storageBucket: 'notiskku-database.firebasestorage.app',
    iosBundleId: 'com.example.firestoreTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq-Od_xMN-X82rQN67CdoWN0q0w-98DKs',
    appId: '1:816941767036:ios:06d40165f9dc685277ecf9',
    messagingSenderId: '816941767036',
    projectId: 'notiskku-database',
    storageBucket: 'notiskku-database.firebasestorage.app',
    iosBundleId: 'com.example.firestoreTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOq4HcsFkWTTgxbLYId1mfoKakZSIluYI',
    appId: '1:816941767036:web:7b412cfc59dc785b77ecf9',
    messagingSenderId: '816941767036',
    projectId: 'notiskku-database',
    authDomain: 'notiskku-database.firebaseapp.com',
    storageBucket: 'notiskku-database.firebasestorage.app',
  );
}
